import generated from "./snippets.generated.json";

export type SlideSnippet = {
  file: string;
  lang: string;
  first: number;
  last: number;
  href: string;
  html: string;
};

// Regenerated by `npm run tour:sync`; the docs build fails when it is stale.
export const slideSnippets: Record<string, SlideSnippet> = generated;

export function slideSnippet(id: string): SlideSnippet {
  const snippet = slideSnippets[id];
  if (!snippet) throw new Error(`Unknown slide snippet "${id}". Add a tour:begin ${id} marker.`);
  return snippet;
}
